stages:
  validate:
    cmd: python src/data_validation.py
    deps:
      - s3://prodyot-edu-data-mlproject/data/raw/reviews.csv

  preprocess:
    cmd: python src/preprocessing.py
    deps:
      - s3://prodyot-edu-data-mlproject/data/raw/reviews.csv
    outs:
      - s3://prodyot-edu-data-mlproject/data/processed/clean.csv:
          persist: true

  train:
    cmd: python src/train.py
    deps:
      - s3://prodyot-edu-data-mlproject/data/processed/clean.csv
    outs:
      - models/model.pkl