apiVersion: apps/v1
kind: Deployment
metadata:
  name: prodyot-api-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: prodyotsarkar/prodyot-mlops830api:latest
        ports:
        - containerPort: 8000
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_DEFAULT_REGION
---
apiVersion: v1
kind: Service
metadata:
  name: prodyot-api-svc
spec:
  selector:
    app: api
  ports:
  - port: 8000
    targetPort: 8000